"""Keep the Architecture.md zoom re-aggregation table in sync with the registry.

The table is generated by ``flexviz.trace.recompute_policy_table()``.  This test
fails whenever a trace's ``recompute_policy_doc`` changes (or a trace is added)
without regenerating the embedded block — pasting the table function's output
between the markers fixes it.
"""

from __future__ import annotations

from pathlib import Path

from flexviz.trace import recompute_policy_table, select_policy_table

_ARCHITECTURE = Path(__file__).resolve().parent.parent / "Architecture.md"


def _embedded_table(start: str, end: str) -> str:
    text = _ARCHITECTURE.read_text(encoding="utf-8")
    assert start in text and end in text, "policy markers missing from Architecture.md"
    block = text.split(start, 1)[1].split(end, 1)[0]
    return block.strip()


def test_recompute_policy_table_matches_docs():
    embedded = _embedded_table(
        "<!-- recompute-policy:start -->", "<!-- recompute-policy:end -->"
    )
    assert embedded == recompute_policy_table(), (
        "Architecture.md recompute-policy table is stale; regenerate it from "
        "flexviz.trace.recompute_policy_table()."
    )


def test_select_policy_table_matches_docs():
    embedded = _embedded_table(
        "<!-- select-policy:start -->", "<!-- select-policy:end -->"
    )
    assert embedded == select_policy_table(), (
        "Architecture.md select-policy table is stale; regenerate it from "
        "flexviz.trace.select_policy_table()."
    )


def test_every_registered_trace_appears():
    from flexviz.trace import _REGISTRY

    recompute = recompute_policy_table()
    select = select_policy_table()
    for trace_type in _REGISTRY:
        assert f"`{trace_type}`" in recompute
        assert f"`{trace_type}`" in select
